name:                tf
version:             0.1.0.0
github:              "oscarvarto/tf"
license:             BSD3
author:              "Oscar Vargas Torres"
maintainer:          "vargas.torres.oscar@gmail.com"
copyright:           "Copyright (c) 2018 Oscar Vargas Torres"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Machine Learning

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/oscarvarto/tf#readme>

dependencies:
- base >= 4.7 && < 5
- tensorflow
- tensorflow-core-ops
- tensorflow-logging
- tensorflow-opgen
- tensorflow-ops
- tensorflow-proto
- tensorflow-mnist
- tensorflow-mnist-input-data
- tensorflow-records
- tensorflow-records-conduit
- tensorflow-test
- HUnit
- lens-family
- transformers
- random
- text
library:
  source-dirs: src

executables:
  tf-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tf
    - tensorflow
    - tensorflow-core-ops
    - tensorflow-logging
    - tensorflow-opgen
    - tensorflow-ops
    - tensorflow-proto
    - tensorflow-mnist
    - tensorflow-mnist-input-data
    - tensorflow-records
    - tensorflow-records-conduit
    - tensorflow-test
    - HUnit
    - lens-family
    - transformers
    - random

tests:
  tf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tf
